### ISSUE TITLE
paginatorヘルパでurlオプションにnullを渡すとページングURLがactionまでになる

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/NetCommons#26]
https://github.com/NetCommons3/NetCommons/blob/master/View/Elements/paginator.ctp#L20
31行、36行も同じ。

このelementを使うときに

```php
$this->element('NetCommons.paginator')
```
だけだとページングのURLはaction名まで（ページ番号はnamedで入るけど）でframeIdや自前で指定しているnamedパラメータがURLに入らない。

自前指定してるパラメータ等を入れようと思うとurlオプションの利用が必須になる。

Blogsプラグインではリストでで
blog_entries/index/6/category_id:1
blog_entries/year_month/6/year_month:2015-06
blog_entries/tag/6/tag_id:1
のようにURLパラメータのパターンがいくつかあるので全部urlオプションで明示するのは避けたい。

$url指定なしのときは、urlオプションにnullセットでなくurlオプション無指定にしてほしい

**Comment by kteraguchi** [comment]
あれっ。nullのセットでダメ？？と思い、ちょいと見てみました。
PaginatorHelper::link
```
if (!empty($this->options)) {
	$options += $this->options;
}
```
おぉぉ、加算演算か。。。

そもそもテストコードは？。。。。むむっ、ない。。。。
