### ISSUE TITLE
Workflow周り

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons#31]
現状、各プラグイン側で実装しているが共通化できる部分があるので、あげておきます。

・コンテンツ登録処理
　　PublishableBehavior::beforeSaveで実装済み（テスト30.65%）
　　Created(作成者)の登録処理も入れときたい。

・コンテンツ取得処理
　　BlogEntry::getConditions
     BbsArticlesComponent::setConditions
     FaqQuestionsController::__setConditions
　　・・・
     で実装済み

・コンテンツ編集リンク表示処理
　　Blogs\View\Elements\BlogEntries\edit_link.ctp
     Bbses\View\Elements\BbsArticles\edit_link.ctp
　　・・・
     で実装済み

・コンテンツ登録ボタン表示処理
　　NetCommons\View\Elements\workflow_buttons.ctp
     で実装済み

・コンテンツ登録画面表示Validation
　　NetCommonsRoomRole::startup
     BlogEntriesEditController::edit
     で実装済み

・権限登録処理
    NetCommonsBlockComponent::getBlockRolePermissions
    プラグイン名BlockRolePermissionsController
    で実装済み

Workflow機能としてまとめたい。
Workflowプラグインとして切り出した方が良い気がする。

**Comment by kteraguchi** [comment]
ブログプラグインで、編集リンクの表示判断修正。
共通化時注意
https://github.com/NetCommons3/Blogs/commit/461007ce9660f672877655f76af96c8375ff5414#diff-9eb83a4bfa6454475d20b5420e2fbf83

**Comment by s-nakajima** [comment]
共通化したためclonse
