### ISSUE TITLE
各プラグインのURLについて

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/NetCommons#37]
現状各プラグインはframe_idをキーにして処理しています。
frame_idをキーにすると、配置しているブロックを変更すると内容がずれます。

以前に
「フレームに配置されていなくても、コンテンツを指すURLで参照できるようにしましょう」
＃ NC2と違う動作
という話が当たったと思います。

ルーム機能も着手し始めていますので、それも含めたURLの再設計が必要です。

**Comment by kteraguchi** [comment]
もくもく会で検討したURLの案をあげときます。

http://example.com/PluginName/ControllerName/block_id/content_id/

ページプラグインから呼び出す場合はframe_idをパラメータとしてつける
Ex.frame_id:999

これでOKとなると、Frameの削除が論理削除だが物理削除でOKですね。

以下も確認が必要です。
・上記URLをリンクした際のヘッダー、左右、フッターは、
　block_idに紐づくroom_idのトップページのもので良い？
・フレーム枠の色はデフォルト、フレームタイトルはプラグイン名で良い？

うーん。やっぱblock_idからframe_idたどらないとダメかな。
複数取れるのでidが小さいほう優先とかかな。

**Comment by RyujiAMANO** [comment]
> うーん。やっぱblock_idからframe_idたどらないとダメかな。

ブロックからフレームをたどらないと後々いろいろ破綻しそうな予感がしてます。

> 複数取れるのでidが小さいほう優先とかかな。

設定できるようにしないと、
1．フレーム1でブロック1表示
2．フレーム2でもブロック1表示
3．フレーム1を間違って削除
4．フレーム1があったところにフレーム3を設置してブロック1表示
ってして、フレーム3をメインとして表示させたくても、できなくなっちゃいます。

ほとんどのケースではブロック1に対してフレーム1で使われるだろうから、どう設定させるのがいいのかUIはすぐには思いつかないのですが、ブロックに優先フレームを指定させた方がいいだろうと思います。

**Comment by kteraguchi** [comment]
> ブロックからフレームをたどらないと後々いろいろ破綻しそうな予感がしてます。

やっぱそうですよね。共通前処理でたどるようにします。

> ブロックに優先フレームを指定させた方がいいだろうと思います。

確かに、プログラム内で固定してしまうのは融通効かなくなりますね。
blocksテーブルにpriority_frame_id追加します。
後はUI部分ですが、もくもく会で相談させてください。

**Comment by kteraguchi** [comment]
本日話合いました。

> http://example.com/PluginName/ControllerName/block_id/content_id/
> ページプラグインから呼び出す場合はframe_idをパラメータとしてつける

・複数のFrameが取れた場合は、id小さいほう優先。
・Frameがない場合はデフォルトを使用。

で決定。
