### ISSUE TITLE
フォトアルバムでの画像（Exif データなし）表示

### ISSUE THREAD

**Issue by horitada** [NetCommons3/NetCommons#468]
NC2を移行時に判明したのですが、古い画像ですとExif データが無く、縦横がズレて表示されます。
NC2の場合には縦横は正しく（人の目には）表示されておりました。

**Comment by akagane99** [comment]
https://github.com/NetCommons3/NetCommons3/issues に転記しました。
上記issueにまとめているので、こちらはクローズします。
